language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --prefer-dist --dev

script:
  - /usr/bin/php ./vendor/phpunit/phpunit/phpunit --configuration ./tests/phpunit.xml --teamcity
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/
